variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

test:
  image: "julia:1"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH # Pkg3.jl#325
    - julia --project -e 'using Pkg;
                          Pkg.clone(pwd(), "PuMaS");
                          Pkg.build("PuMaS");
                          Pkg.test("PuMaS"; coverage=true);'